apiVersion: v2
name: cluster-issuer
description: Mint System Cluster Issuer
home: https://kubernetes.build
maintainers:
  - name: Mint System GmbH
    email: support@mint-system.ch
type: application
version: 0.1.0
appVersion: "1.0.0"
