{{- if eq .Values.acme.solver "infomaniak" }}
apiVersion: v1
kind: Secret
metadata:
  name: infomaniak-api-token
  namespace: cert-manager
data:
  api-token: {{ .Values.acme.infomaniakApiToken | toString | b64enc | quote }}
{{- end }}
