apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-int
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }}
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-int
    solvers:
    {{- if eq .Values.acme.solver "http01" }}
      - http01:
          ingress:
            ingressClassName: nginx
    {{- end }}
    {{- if eq .Values.acme.solver "infomaniak" }}
      - dns01:
          webhook:
            groupName: acme.infomaniak.com
            solverName: infomaniak
            config:
              apiTokenSecretRef:
                name: infomaniak-api-token
                key: api-token
    {{- end }}
