apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }}
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    {{- if eq .Values.acme.solver "http01" }}
    - http01:
        ingress:
          ingressClassName: nginx
    {{- end }}
    {{- if eq .Values.acme.solver "infomaniak" }}
    - dns01:
        webhook:
          groupName: acme.infomaniak.com
          solverName: infomaniak
          config:
            apiTokenSecretRef:
              name: infomaniak-api-credentials
              key: api-token
              namespace: cert-manager
    {{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }}
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    {{- if eq .Values.acme.solver "http01" }}
    - http01:
        ingress:
          ingressClassName: nginx
    {{- end }}
    {{- if eq .Values.acme.solver "infomaniak" }}
    - dns01:
        webhook:
          groupName: acme.infomaniak.com
          solverName: infomaniak
          config:
            apiTokenSecretRef:
              name: infomaniak-api-credentials
              key: api-token
              namespace: cert-manager
    {{- end }}
