apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-updater-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-updater-rolebinding
roleRef:
  name: deployment-updater-role
  kind: Role
subjects:
- kind: ServiceAccount
  name: deployment-updater
  namespace: default
