## @section vshnPostgres parameters
##
## @param enabled Enable or disable vshnPostgres
##
enabled: false
## @param secretRef The secret reference for vshnPostgres
##
secretRef: postgres-creds
client:
  ## @param client.enabled Enable or disable the vshnPostgres client
  ##
  enabled: false
## @section Resources requests and limits
resources:
  ## @param resources.requests.memory Memory request for the container
  requests:
    memory: "500Mi"
    ## @param resources.requests.cpu CPU request for the container
    cpu: "100m"
  limits:
    ## @param resources.limits.memory Memory limit for the container
    memory: "1Gi"
