apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: deploy
  name: deploy-sa-token
  namespace: default
type: kubernetes.io/service-account-token
