apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app: s3
type: Opaque
data:
  endpoint: {{ .Values.endpoint | b64enc | quote }}
  bucket: {{ .Values.bucket | b64enc | quote }}
  {{- $usernameKey := .Values.usernameKey }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.name }}
  {{- if and $existingSecret (index $existingSecret.data $usernameKey) }}
  {{ $usernameKey }}: {{ index $existingSecret.data $usernameKey }}
  {{- else }}
  {{ $usernameKey }}: {{ .Values.username | default (randAlphaNum 20) | b64enc | quote }}
  {{- end }}
  {{- $passwordKey := .Values.passwordKey }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.name }}
  {{- if and $existingSecret (index $existingSecret.data $passwordKey) }}
  {{ $passwordKey }}: {{ index $existingSecret.data $passwordKey }}
  {{- else }}
  {{ $passwordKey }}: {{ .Values.password | default (randAlphaNum 20) | b64enc | quote }}
  {{- end }}
