apiVersion: v2
name: odoo
description: Mint System Odoo
home: https://kubernetes.build/
maintainers:
  - name: Mint System GmbH
    email: support@mint-system.ch
type: application
version: 0.1.0
appVersion: "1.0.0"
templates:
  - odoo-cm.yaml
  - odoo-svc.yaml
  - odoo-deploy.yaml

