---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: mintsystem/odoo:16.0.20250207
          ports:
          - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-config
      initContainers:
        - name: git-clone-addons
          image: mintsystem/odoo:16.0.20250207
          command: ["/entrypoint.sh", "git-clone-addons"]
          envFrom:
            - configMapRef:
                name: odoo-config
        - name: init-db
          image: mintsystem/odoo:16.0.20250207
          acommand: ["/entrypoint.sh", "odoo-config"]
          envFrom:
            - configMapRef:
                name: odoo-config
