## @section K8up parameters
##
k8up:
  ## @param k8up.enabled Enable or disable K8up
  ##
  enabled: false

## @section Staging parameters
##
staging:
  ## @param staging.enabled Enable or disable staging deployment
  ##
  enabled: false
  ## @param staging.name Name of the staging environment
  ##
  name: staging
  ## @param staging.host Host for staging ingress
  ##
  host: staging.odoo.cloud.local