{{- if and .Values.k8up.enabled .Values.cnpg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup-repo
  labels:
    app: nextcloud
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-backup-repo" .Release.Name) }}
  {{- if and $existingSecret (index $existingSecret.data "password") }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  password:  {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: {{ .Release.Name }}-nextcloud-backup
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: {{ .Release.Name }}-backup-repo
      key: password
    s3:
      endpoint: {{ .Values.k8up.endpoint }}
      bucket: {{ .Values.k8up.bucket }}/{{ .Values.ingress.host }}
      accessKeyIDSecretRef:
        name: s3-credentials
        key: username
      secretAccessKeySecretRef:
        name: s3-credentials
        key: password
  schedule: "0 2 * * *"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
{{- end }}