apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: nextcloud
data:
  NEXTCLOUD_TRUSTED_DOMAINS: "{{ .Values.ingress.host }}{{- if .Values.ingress.customDomain }} {{ .Values.ingress.customDomain }}{{- end }}"