apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  NEXTCLOUD_ADMIN_USER: {{ .Values.adminUser | quote }}
  NEXTCLOUD_ADMIN_PASSWORD: {{ .Values.adminPassword | quote }}
  NEXTCLOUD_TRUSTED_DOMAINS: {{ .Values.ingress.host | quote }}