{{- if and .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ default (printf "%s-postgresql" .Release.Name) .Values.cnpg.nameOverride }}
  labels:
    app: nextcloud
    release: {{ .Release.Name }}
spec:
  instances: {{ .Values.cnpg.instances }}
  storage:
    size: {{ .Values.cnpg.storage.size }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database }}
      owner: {{ .Values.cnpg.owner }}
{{- end }}