apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-fix-missing-indices
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: nextcloud-occ
        image: {{ .Values.image }}
        command: ["/bin/bash", "-c"]
        args:
          - |
            sleep 30  # Wait for Nextcloud to be fully ready
            php occ db:add-missing-indices --no-interaction
        env:
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud-creds
                key: NEXTCLOUD_ADMIN_USER
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-creds
                key: NEXTCLOUD_ADMIN_PASSWORD
          {{- if .Values.cnpg.enabled }}
          - name: POSTGRES_DB
            value: {{ .Values.cnpg.database }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql-app
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql-app
                key: password
          - name: POSTGRES_HOST
            value: {{ .Release.Name }}-postgresql-rw.{{ .Release.Namespace }}.svc.cluster.local
          {{- end }}
        volumeMounts:
          - name: nextcloud-data
            mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-nextcloud-data