apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: 10Gi