apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
  labels:
    app: postgres
immutable: true
data:
  port: {{ .Values.port | toString | b64enc | quote }}
  db: {{ .Values.db | b64enc | quote }}
  user: {{ .Values.user | b64enc | quote }}
  {{ .Values.userPasswordKey }}: {{ .Values.password | default (randAlphaNum 20) | b64enc | quote }}
