apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretRef }}
  labels:
    app: postgres
data:
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
