apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretRef }}
  labels:
    app: postgres
data:
  host: {{ .Values.postgres.host | b64enc | quote }}
  port: {{ .Values.postgres.port | toString | b64enc | quote }}
  db: {{ .Values.postgres.db | b64enc | quote }}
  user: {{ .Values.postgres.user | b64enc | quote }}
  {{ .Values.postgres.userPasswordKey }}: {{ .Values.postgres.password | toString | b64enc | quote }}
