apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.postgres.secretRef }}
  labels:
    app: postgres
data:
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | toString | b64enc | quote }}
  POSTGRES_DB: {{ "postgres" | b64enc | quote }}
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ randAlphaNum 20 | b64enc | quote }}
