apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
  labels:
    app: postgres
type: Opaque
data:
  port: {{ .Values.port | toString | b64enc | quote }}
  db: {{ .Values.db | b64enc | quote }}
  user: {{ .Values.user | b64enc | quote }}
  {{- $passwordKey := .Values.userPasswordKey }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.secretRef }}
  {{- if and $existingSecret (index $existingSecret.data $passwordKey) }}
  {{ $passwordKey }}: {{ index $existingSecret.data $passwordKey }}
  {{- else }}
  {{ $passwordKey }}: {{ .Values.password | default (randAlphaNum 20) | b64enc | quote }}
  {{- end }}
