apiVersion: v2
name: s3
description: Mint System S3
home: https://kubernetes.build
maintainers:
  - name: Mint System GmbH
    email: support@mint-system.ch
type: application
version: 0.1.0
appVersion: "1.0.0"
