{{- if .Values.cnpg.cluster.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ default (printf "%s-postgresql" .Release.Name) .Values.cnpg.cluster.nameOverride }}
spec:
  instances: {{ .Values.cnpg.cluster.instances }}
  storage:
    size: {{ .Values.cnpg.cluster.storage.size }}
{{- end }}

{{- if .Values.cnpg.database.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Release.Name }}-database
spec:
  name: {{ .Values.cnpg.database.name }}
  cluster:
    name: {{ default (printf "%s-postgresql" .Release.Name) .Values.cnpg.cluster.nameOverride }}
---
apiVersion: postgresql.cnpg.io/v1
kind: SQL
metadata:
  name: odoo-db-access
  namespace: default
spec:
  cluster:
    name: {{ default (printf "%s-postgresql" .Release.Name) .Values.cnpg.cluster.nameOverride }}
  sql: |
    GRANT CONNECT ON DATABASE odoo TO app;
    GRANT USAGE ON SCHEMA public TO app;
    GRANT CREATE ON SCHEMA public TO app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO app;
{{- end }}
