{{- if and .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  instances: 1
  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Release.Name }}-database
spec:
  name: {{ .Values.database }}
  cluster:
    name: {{ .Release.Name }}-postgresql
{{- end }}
