apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.odoo.configMapRef }}
  labels:
    app: odoo
data:
  GITHUB_USERNAME: {{ .Values.odoo.githubUsername | quote }}
  ADDONS_GIT_REPOS: {{ .Values.odoo.addonsGitRepos | quote }}
  ODOO_INIT_LANG: {{ .Values.odoo.initLang | quote }}
  PROXY_MODE: {{ .Values.odoo.proxyMode | quote }}
  LIST_DB: {{ .Values.odoo.listDB | quote }}
