---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: git-clone-addons
          image: {{ .Values.odoo.image }}
          command: [ "git-clone-addons" ]
          envFrom:
            - secretRef:
                name: odoo-creds
            - configMapRef:
                name: odoo-config
        - name: init-db
          image: {{ .Values.odoo.image }}
          command: [ "init-db" ]
          envFrom:
            - secretRef:
                name: odoo-creds
            - configMapRef:
                name: odoo-config
      containers:
        - name: {{ .Values.odoo.host }}
          image: {{ .Values.odoo.image }}
          ports:
          - containerPort: 8069
          envFrom:
            - secretRef:
                name: odoo-creds
            - configMapRef:
                name: odoo-config
