---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.postgres.image }}
          command: [ "sh", "-c", "until pg_isready -h postgres -p 5432; do sleep 2; done" ]
        - name: init
          image: {{ .Values.odoo.image }}
          command:
            - /bin/bash
            - -c
            - |
              /entrypoint.sh git-clone-addons && \
              /entrypoint.sh init-db
          envFrom:
            - configMapRef:
                name: odoo-config
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.odoo.image }}
          ports:
          - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-config
