apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
  labels:
    app: odoo
data:
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ .Values.githubPersonalAccessToken | b64enc | quote }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  labels:
    app: postgresql
data:
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ randAlphaNum 20 | b64enc | quote }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}
