---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-creds
  labels:
    app: odoo
data:
  {{- if .Values.postgres.enabled }}
  PGHOST: {{ .Values.postgres.host | b64enc | quote }}
  PGUSER: {{ .Values.postgres.user | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  ODOO_DATABASE: {{ .Values.odoo.database | b64enc | quote }}
  {{- end }}
  {{- if .Values.vshnpostgresql.enabled }}
  PGHOST: '{{ (lookup "v1" "Secret" .Release.Namespace "postgresql-creds").data.POSTGRESQL_HOST | b64dec }}'
  PGUSER: '{{ (lookup "v1" "Secret" .Release.Namespace "postgresql-creds").data.POSTGRESQL_USER | b64dec }}'
  PGPASSWORD: '{{ (lookup "v1" "Secret" .Release.Namespace "postgresql-creds").data.POSTGRESQL_PASSWORD | b64dec }}'
  ODOO_DATABASE: '{{ (lookup "v1" "Secret" .Release.Namespace "postgresql-creds").data.POSTGRESQL_DB | b64dec }}'
  {{- end }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ .Values.odoo.githubPersonalAccessToken | b64enc | quote }}
