---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-creds
  labels:
    app: odoo
data:
  PGHOST: {{ .Values.postgres.host | b64enc | quote }}
  PGUSER: {{ .Values.postgres.user | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgres.password | b64enc | quote }}