---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  labels:
    app: odoo
data:
  PROXY_MODE: {{ .Values.odoo.proxyMode | quote }}
  ADDONS_GIT_REPOS: {{ .Values.odoo.addonsGitRepos | quote }}
  ODOO_INIT_LANG: {{ .Values.odoo.initLang | quote }}
  LIST_DB: {{ .Values.odoo.listDB | quote }}