---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: init
          image: {{ .Values.odoo.image }}
          command:
            - /bin/bash
            - -c
            - |
              {{- if .Values.odoo.downloadOdooEnterprise }}/entrypoint.sh download-odoo-enterprise && \{{- end }}
              /entrypoint.sh git-clone-addons && \
              /entrypoint.sh init-db
          envFrom:
            - secretRef:
                name: odoo-creds
            - configMapRef:
                name: odoo-config
      containers:
        - name: {{ .Values.odoo.host }}
          image: {{ .Values.odoo.image }}
          ports:
          - containerPort: 8069
          envFrom:
            - secretRef:
                name: odoo-creds
            - configMapRef:
                name: odoo-config
