apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-odoo-main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
{{- if .Values.staging.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-odoo-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
{{- end }}