apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
  labels:
    app: odoo
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.secretRef }}
  {{- if and $existingSecret (index $existingSecret.data "GITHUB_PERSONAL_ACCESS_TOKEN") }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ index $existingSecret.data "GITHUB_PERSONAL_ACCESS_TOKEN" }}
  {{- else }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ .Values.githubPersonalAccessToken | b64enc | quote }}
  {{- end }}
{{- if and .Values.postgresql.enabled (not (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.auth.existingSecret)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  labels:
    app: postgresql
data:
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ randAlphaNum 20 | b64enc | quote }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}

