---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.postgres.image }}
          command: [ "sh", "-c", "until pg_isready -h postgres -p 5432; do sleep 2; done" ]
        - name: git-clone-addons
          image: {{ .Values.odoo.image }}
          command: ["/entrypoint.sh", "git-clone-addons"]
          envFrom:
            - configMapRef:
                name: odoo-config
        - name: init-db
          image: {{ .Values.odoo.image }}
          command: ["/entrypoint.sh", "init-db"]
          envFrom:
            - configMapRef:
                name: odoo-config
      containers:
        - name: odoo
          image: {{ .Values.odoo.image }}
          ports:
          - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-config
